# Generated by Django 4.0.3 on 2022-04-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='guestion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='suject',
            new_name='subject',
        ),
    ]
